### ISSUE TITLE
should biopam be independent of main opam-repository

### ISSUE THREAD

**Issue by agarwal** [solvuu/biopam#11]
@rleonid submitted packages depending on `conf-python-2-7`, which exists only in the main [opam-repository for OCaml packages](https://github.com/ocaml/opam-repository). Thus far we've been treating biopam as independent from that. Should we continue to do so? One argument in favor of remaining independent is that many bioinformaticians who will be interested in biopam are not OCaml programmers.

**Comment by pveber** [comment]
I'd rather keep the two repos independent, at least for readability purpose: having our packages for bioinformatics tools lost in the middle of hundred of ocaml libraries by default does not seem right.

However, we should maintain the two repos compatible, that is watch for name collisions. Detecting them systematically would be a first step. Then upon detection, if two packages have the same name but do different things, it's easy, we can rename the one in biocaml. However the case of `conf-python` seems more difficult to me. Maybe ensure (again in an automated way) that our conf-python-2-7 is in sync with opam's one?

**Comment by agarwal** [comment]
> we should maintain the two repos compatible, that is watch for name collisions. Detecting them systematically would be a first step.

That should be easy enough. We can simply add a `lint` sub-command to `biocaml-dev.ml`. This could be one of several things it checks.

> Maybe ensure (again in an automated way) that our conf-python-2-7 is in sync with opam's one?

Also easy. We can add an `import` command to `biocaml-dev.ml`, which copies a package from the main OCaml opam-repository. Since that repo (and biopam) are licensed under CC0, there is no complication and no further work (e.g. adding an attribution) is required.

**Comment by pveber** [comment]
I'm assuming you meant `biopam-dev.ml`, right?

These commands would be great additions I think, even better if the `lint` command can be run from a github PR. They would not help though in case of changes on the official opam repo, like suddently creating a `conf-R` package, but I think they would sufficient "almost surely".

**Comment by agarwal** [comment]
> I'm assuming you meant biopam-dev.ml, right?

Right, fixed the typo.

**Comment by rleonid** [comment]
:+1: For independence. I don't mind explicitly replicating the `conf-python-2-7` package here so that our repo is self contained.

**Comment by agarwal** [comment]
Ok, so for now go ahead and manually copy it. We can automate later.
